apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-opa-policy
  labels:
    app: {{ .Values.app.name }}-opa-policy
    domain: {{ .Values.app.domain }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9252"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-opa-policy
      domain: {{ .Values.app.domain }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-opa-policy
        domain: {{ .Values.app.domain }}
      annotations:
      {{ if .Values.app.linkerd.enabled }}
        linkerd.io/inject: enabled
      {{ end }}
    spec:
      serviceAccountName: sa-{{ .Values.app.name }}
      containers:
        - name: web-app
          image: {{ .Values.app.opa_policy.container.image }}
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
