---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ .Values.app.name }}
  labels:
{{ include "service.labels" . | indent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: r-cluster-managers-{{ .Values.app.name }}
  labels:
{{ include "service.labels" . | indent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
      - pods/log
      - statefulsets
      - endpoints
      - services
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-cluster-managers-{{ .Values.app.name }}
  labels:
{{ include "service.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: r-cluster-managers-{{ .Values.app.name }}
subjects:
  - kind: ServiceAccount
    name: sa-{{ .Values.app.name }}
    namespace: {{ .Release.Namespace }}

---
