---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-opa-policy
  labels:
{{ include "service.labels" . | indent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: {{ .Values.app.opa_policy.http.port }}
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    app: {{ .Values.app.name }}-opa-policy
    domain: {{ .Values.app.domain }}
  type: ClusterIP

---
